export interface IEmpl {
  employeeID: number;
  firstName: string;
  lastName: string;
  fatherName: string;
  birthDate: string;
  homeAddress: string;
  date0: string;
  date1: string;
  sex: string;
  dismissalDate: string;
  dismissalDocDate: string;
  dismissalDocNumer: string;
  dismissalReason: string;
  education: string;
  employmentDate: string;
  nationality: string;
  tradeUnionName: string;
  passportNumber: string;
  passportDateStart: string;
  passportMade: string;
  personalNumber: string;
  addressindex: string;
  phoneNumber: string;
  smtn0: string;
  smtn1: string;
  smtn2: string;
  smtn3: string;
}
